apiVersion: v1
kind: Secret
metadata:
  name: cloudcreators-secret
  namespace: cloudcreators
type: Opaque
stringData:
  MONGO_URI: ""
  FERNET_KEY: ""
  AZURE_CLIENT_ID: ""
  AZURE_TENANT_ID: "-"
  AZURE_REDIRECT_URI: ""
  AZURE_CLIENT_SECRET: ""
  BIGQUERY_BILLING_TABLE: ""
